# Example job that ...
# - moves new files in '/inbox' to '/outbox' every 5 seconds
# - cleanup moved files in '/outbox' that are older than 20 seconds
action: move
cron: "*/5 * * * * *"
source:
  dir: /inbox
  includes:
    - "**/**"
  excludes:
    - "**/.*"
    - "**/*.log"
target:
  dir: /outbox
  retention: "20s"
