action: copy # exec | copy | move | delete | archive
cron: "*/5 * * * * *"
source:
  dir: /src
  includes:
    - "**/*.ts"
  excludes:
    - "**/*test.ts"
target:
  dir: $1/build/example/backup
  permissions:
    owner: "1000:1000"
    file_mode: "664"
    dir_mode: "774"
  retention: "10d"
verbose: false
enabled: false
