# THIS FILE MAY BE OBSOLETE!
# WHY? Use env vars for config
# - CROPS_SOURCE_EXCLUDES: "[**/*~, **/*~]"
# - CROPS_EXEC_ENVIRONMENT: "[CI_API_TOKEN:'10f23f2efasdfsevrew']"
# - CROPS_EXEC_SHELL: "/bin/bash"
# - CROPS_DEFAULT_ARCHIVE_NAME

# Altenatively:
# - any environment will be routed to the sub process
# - CROPS_EXEC_APPLY_PARENT_ENVIRONMENT
#
# Notes:
# - Needs a server restart if changes to this file are made
useShell: false
environment:
  - CI_API_TOKEN=""
source:
  excludes:
    - "**/*~"
    - "**/*.git"
    - "**/*.svn"
    - "**/*.part"
    - "**/*.download"
    - "**/*.crdownload"
    - "**/*.tmp"
target:
  archive_name: "backup-{{yyyy-MM-dd_HH-mm}}.tgz"
