name: Node.js Test im Container

on:
  push:
    branches: [ main ]

jobs:
  test-in-docker:
    runs-on: ubuntu-latest 

    container:
      image: node:24-alpine 

    steps:
        # Checkout to /__w/REPO/REPO
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Install modules
        run: npm ci

      - name: Check code 
        run: npm run check

      - name: Run Tests
        run: npm run test
