name: Release to ghcr.io

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push cronops image
        uses: docker/build-push-action@v5
        with:
          push: true
          target: app
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/cronops:latest
            ghcr.io/${{ github.repository_owner }}/cronops:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build & push cronops-docs image
        uses: docker/build-push-action@v5
        with:
          push: true
          target: docs
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/cronops-docs:latest
            ghcr.io/${{ github.repository_owner }}/cronops-docs:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
